version: '3.7'
services:
  grafana:
    image: grafana/grafana-enterprise:${GR_VERSION:-9.4.3}
    # image: grafana/grafana-enterprise:9.2.1
    # image: grafana/grafana-enterprise:latest
    # image: grafana/grafana-enterprise:main
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-databend-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT

  minio:
    image: bitnami/minio
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
      - MINIO_DEFAULT_BUCKETS=databend
    ports:
      - '${MINIO_ENDPOINT_PORT:-9000}:9000'
      - '${MINIO_CONSOLE_PORT:-9001}:9001'
  databend:
    image: 'datafuselabs/databend'
    environment:
      - QUERY_DEFAULT_USER=databend
      - QUERY_DEFAULT_PASSWORD=databend
      - QUERY_STORAGE_TYPE=s3
      - AWS_S3_ENDPOINT=http://127.0.0.1:${MINIO_ENDPOINT_PORT:-9000}
      - AWS_S3_BUCKET=databend
      - AWS_ACCESS_KEY_ID=ROOTUSER
      - AWS_SECRET_ACCESS_KEY=CHANGEME123
    # github.com/databendcloud/databend-go uoload data to minio directly, so we need to use host network
    network_mode: host
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - minio
